# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lenovo/adder/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lenovo/adder/proprietary/bin/6620_launcher:system/bin/6620_launcher \
    vendor/lenovo/adder/proprietary/bin/bmc156d:system/bin/bmc156d \
    vendor/lenovo/adder/proprietary/bin/ccci_fsd:system/bin/ccci_fsd \
    vendor/lenovo/adder/proprietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
    vendor/lenovo/adder/proprietary/bin/drvbd:system/bin/drvbd \
    vendor/lenovo/adder/proprietary/bin/gsm0710muxd:system/bin/gsm0710muxd \
    vendor/lenovo/adder/proprietary/bin/lsm303md:system/bin/lsm303md \
    vendor/lenovo/adder/proprietary/bin/md_ctrl:system/bin/md_ctrl \
    vendor/lenovo/adder/proprietary/bin/msensord:system/bin/msensord \
    vendor/lenovo/adder/proprietary/bin/mtk_agpsd:system/bin/mtk_agpsd \
    vendor/lenovo/adder/proprietary/bin/mtkrild:system/bin/mtkrild \
    vendor/lenovo/adder/proprietary/bin/muxreport:system/bin/muxreport \
    vendor/lenovo/adder/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
    vendor/lenovo/adder/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    vendor/lenovo/adder/proprietary/bin/thermal_manager:system/bin/thermal_manager \
    vendor/lenovo/adder/proprietary/bin/wmt_loader:system/bin/wmt_loader \
    vendor/lenovo/adder/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
    vendor/lenovo/adder/proprietary/etc/firmware/ROMv1_patch_1_0_hdr.bin:system/etc/firmware/ROMv1_patch_1_0_hdr.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/ROMv1_patch_1_1_hdr.bin:system/etc/firmware/ROMv1_patch_1_1_hdr.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/WIFI_RAM_CODE_SOC:system/etc/firmware/WIFI_RAM_CODE_SOC \
    vendor/lenovo/adder/proprietary/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg \
    vendor/lenovo/adder/proprietary/etc/firmware/catcher_filter_1_wg_n.bin:system/etc/firmware/catcher_filter_1_wg_n.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/modem.img:system/etc/firmware/modem.img \
    vendor/lenovo/adder/proprietary/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/mt6627/mt6627_fm_v1_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/mt6627/mt6627_fm_v2_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/mt6627/mt6627_fm_v3_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/mt6627/mt6627_fm_v4_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin \
    vendor/lenovo/adder/proprietary/etc/firmware/mt6627/mt6627_fm_v5_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin \
    vendor/lenovo/adder/proprietary/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
    vendor/lenovo/adder/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/lenovo/adder/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/lenovo/adder/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/lenovo/adder/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/lenovo/adder/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/lenovo/adder/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/lenovo/adder/proprietary/lib/hw/audio.primary.mt6582.so:system/lib/hw/audio.primary.mt6582.so \
    vendor/lenovo/adder/proprietary/lib/hw/camera.mt6582.so:system/lib/hw/camera.mt6582.so \
    vendor/lenovo/adder/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/lenovo/adder/proprietary/lib/hw/gralloc.mt6582.so:system/lib/hw/gralloc.mt6582.so \
    vendor/lenovo/adder/proprietary/lib/hw/hwcomposer.mt6582.so:system/lib/hw/hwcomposer.mt6582.so \
    vendor/lenovo/adder/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    vendor/lenovo/adder/proprietary/lib/hw/sensors.mt6582.so:system/lib/hw/sensors.mt6582.so \
    vendor/lenovo/adder/proprietary/lib/hw/memtrack.mt6582.so:system/lib/hw/memtrack.mt6582.so \
    vendor/lenovo/adder/proprietary/lib/hw/radio.fm.mt6582.so:system/lib/hw/radio.fm.mt6582.so \
    vendor/lenovo/adder/proprietary/lib/lib3a.so:system/lib/lib3a.so \
    vendor/lenovo/adder/proprietary/lib/lib3a_sample.so:system/lib/lib3a_sample.so \
    vendor/lenovo/adder/proprietary/lib/libaed.so:system/lib/libaed.so \
    vendor/lenovo/adder/proprietary/lib/libfmjni.so:system/lib/libfmjni.so \
    vendor/lenovo/adder/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    vendor/lenovo/adder/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxAdpcmDec.so:system/lib/libMtkOmxAdpcmDec.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxAdpcmEnc.so:system/lib/libMtkOmxAdpcmEnc.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxAlacDec.so:system/lib/libMtkOmxAlacDec.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxApeDec.so:system/lib/libMtkOmxApeDec.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxFlacDec.so:system/lib/libMtkOmxFlacDec.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxG711Dec.so:system/lib/libMtkOmxG711Dec.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxGsmDec.so:system/lib/libMtkOmxGsmDec.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxRawDec.so:system/lib/libMtkOmxRawDec.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxVdec.so:system/lib/libMtkOmxVdec.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
    vendor/lenovo/adder/proprietary/lib/libMtkOmxVorbisEnc.so:system/lib/libMtkOmxVorbisEnc.so \
    vendor/lenovo/adder/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    vendor/lenovo/adder/proprietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
    vendor/lenovo/adder/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    vendor/lenovo/adder/proprietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
    vendor/lenovo/adder/proprietary/lib/libaudiomtkdcremoval.so:system/lib/libaudiomtkdcremoval.so \
    vendor/lenovo/adder/proprietary/lib/libaudiopolicymanagerdefault.so:system/lib/libaudiopolicymanagerdefault.so \
    vendor/lenovo/adder/proprietary/lib/libaudiopolicymanager.so:system/lib/libaudiopolicymanager.so \
    vendor/lenovo/adder/proprietary/lib/libaudiopolicyenginedefault.so:system/lib/libaudiopolicyenginedefault.so \
    vendor/lenovo/adder/proprietary/lib/libaudiopolicyservice.so:system/lib/libaudiopolicyservice.so \
    vendor/lenovo/adder/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    vendor/lenovo/adder/proprietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
    vendor/lenovo/adder/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
    vendor/lenovo/adder/proprietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
    vendor/lenovo/adder/proprietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
    vendor/lenovo/adder/proprietary/lib/libbluetooth_mtk_pure.so:system/lib/libbluetooth_mtk_pure.so \
    vendor/lenovo/adder/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/lenovo/adder/proprietary/lib/libbwc.so:system/lib/libbwc.so \
    vendor/lenovo/adder/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/lenovo/adder/proprietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
    vendor/lenovo/adder/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/lenovo/adder/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
    vendor/lenovo/adder/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
    vendor/lenovo/adder/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
    vendor/lenovo/adder/proprietary/lib/libcam.halsensor.so:system/lib/libcam.halsensor.so \
    vendor/lenovo/adder/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/lenovo/adder/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
    vendor/lenovo/adder/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
    vendor/lenovo/adder/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    vendor/lenovo/adder/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    vendor/lenovo/adder/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
    vendor/lenovo/adder/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
    vendor/lenovo/adder/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/lenovo/adder/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/lenovo/adder/proprietary/lib/libcamera_client_mtk.so:system/lib/libcamera_client_mtk.so \
    vendor/lenovo/adder/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/lenovo/adder/proprietary/lib/libcurl.so:system/lib/libcurl.so \
    vendor/lenovo/adder/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    vendor/lenovo/adder/proprietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
    vendor/lenovo/adder/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
    vendor/lenovo/adder/proprietary/lib/libdrmmtkutil.so:system/lib/libdrmmtkutil.so \
    vendor/lenovo/adder/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
    vendor/lenovo/adder/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/lenovo/adder/proprietary/lib/libfmcust.so:system/lib/libfmcust.so \
    vendor/lenovo/adder/proprietary/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
    vendor/lenovo/adder/proprietary/lib/libhwm.so:system/lib/libhwm.so \
    vendor/lenovo/adder/proprietary/lib/libimageio.so:system/lib/libimageio.so \
    vendor/lenovo/adder/proprietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    vendor/lenovo/adder/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/lenovo/adder/proprietary/lib/libion_mtk.so:system/lib/libion_mtk.so \
    vendor/lenovo/adder/proprietary/lib/libm4u.so:system/lib/libm4u.so \
    vendor/lenovo/adder/proprietary/lib/libmnl.so:system/lib/libmnl.so \
    vendor/lenovo/adder/proprietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
    vendor/lenovo/adder/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    vendor/lenovo/adder/proprietary/lib/libmtk_mali_user.so:system/lib/libmtk_mali_user.so \
    vendor/lenovo/adder/proprietary/lib/libmtk_mmutils.so:system/lib/libmtk_mmutils.so \
    vendor/lenovo/adder/proprietary/lib/libmtkcamera_client.so:system/lib/libmtkcamera_client.so \
    vendor/lenovo/adder/proprietary/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
    vendor/lenovo/adder/proprietary/lib/libmtkplayer.so:system/lib/libmtkplayer.so \
    vendor/lenovo/adder/proprietary/lib/libnvram.so:system/lib/libnvram.so \
    vendor/lenovo/adder/proprietary/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
    vendor/lenovo/adder/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    vendor/lenovo/adder/proprietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
    vendor/lenovo/adder/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
    vendor/lenovo/adder/proprietary/lib/libsched.so:system/lib/libsched.so \
    vendor/lenovo/adder/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    vendor/lenovo/adder/proprietary/lib/libssladp.so:system/lib/libssladp.so \
    vendor/lenovo/adder/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/lenovo/adder/proprietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
    vendor/lenovo/adder/proprietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
    vendor/lenovo/adder/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
    vendor/lenovo/adder/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/lenovo/adder/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/lenovo/adder/proprietary/vendor/lib/libWVphoneAPI.so:system/vendor/lib/libWVphoneAPI.so \
    vendor/lenovo/adder/proprietary/vendor/lib/libfrsdk.so:system/vendor/lib/libfrsdk.so \
    vendor/lenovo/adder/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/lenovo/adder/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/lenovo/adder/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/lenovo/adder/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/lenovo/adder/proprietary/xbin/mnld:system/xbin/mnld \
    vendor/lenovo/adder/proprietary/lib/libstlport.so:system/lib/libstlport.so
